from enum import Enum


class AzureRegion(Enum):
    northcentralus = "northcentralus"
    uksouth = "uksouth"
    eastasia = "eastasia"
    japanwest = "japanwest"
    southindia = "southindia"
    southcentralus = "southcentralus"
    centralus = "centralus"
    eastus2 = "eastus2"
    brazilsouth = "brazilsouth"
    swedencentral = "swedencentral"
    northeurope = "northeurope"
    australiasoutheast = "australiasoutheast"
    polandcentral = "polandcentral"
    japaneast = "japaneast"
    centralindia = "centralindia"
    westcentralus = "westcentralus"
    switzerlandnorth = "switzerlandnorth"
    westus2 = "westus2"
    italynorth = "italynorth"
    mexicocentral = "mexicocentral"
    westus3 = "westus3"
    israelcentral = "israelcentral"
    indonesiacentral = "indonesiacentral"
    westus = "westus"
    eastus = "eastus"
    newzealandnorth = "newzealandnorth"
    uaenorth = "uaenorth"
    canadacentral = "canadacentral"
    chinanorth3 = "chinanorth3"
    chinanorth2 = "chinanorth2"
    westeurope = "westeurope"
    canadaeast = "canadaeast"
    spaincentral = "spaincentral"
    francecentral = "francecentral"
    chinaeast2 = "chinaeast2"
    southafricanorth = "southafricanorth"
    australiacentral = "australiacentral"
    ukwest = "ukwest"
    norwayeast = "norwayeast"
    germanywestcentral = "germanywestcentral"
    chinanorth = "chinanorth"
    australiaeast = "australiaeast"
    koreacentral = "koreacentral"
