from enum import Enum


class AzureRegion(Enum):
    australiacentral = "australiacentral"
    australiaeast = "australiaeast"
    australiasoutheast = "australiasoutheast"
    brazilsouth = "brazilsouth"
    canadacentral = "canadacentral"
    canadaeast = "canadaeast"
    centralindia = "centralindia"
    centralus = "centralus"
    chinaeast2 = "chinaeast2"
    chinanorth = "chinanorth"
    chinanorth2 = "chinanorth2"
    chinanorth3 = "chinanorth3"
    eastasia = "eastasia"
    eastus = "eastus"
    eastus2 = "eastus2"
    francecentral = "francecentral"
    germanywestcentral = "germanywestcentral"
    indonesiacentral = "indonesiacentral"
    israelcentral = "israelcentral"
    italynorth = "italynorth"
    japaneast = "japaneast"
    japanwest = "japanwest"
    koreacentral = "koreacentral"
    mexicocentral = "mexicocentral"
    newzealandnorth = "newzealandnorth"
    northcentralus = "northcentralus"
    northeurope = "northeurope"
    norwayeast = "norwayeast"
    polandcentral = "polandcentral"
    southafricanorth = "southafricanorth"
    southcentralus = "southcentralus"
    southindia = "southindia"
    spaincentral = "spaincentral"
    swedencentral = "swedencentral"
    switzerlandnorth = "switzerlandnorth"
    uaenorth = "uaenorth"
    uksouth = "uksouth"
    ukwest = "ukwest"
    westcentralus = "westcentralus"
    westeurope = "westeurope"
    westus = "westus"
    westus2 = "westus2"
    westus3 = "westus3"
