apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scheduler.fullname" . }}-memcached
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  {{- if not .Values.memcached.autoscaling }}
  replicas: {{ .Values.memcached.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scheduler.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: memcached
  template:
    metadata:
      {{- with .Values.memcached.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scheduler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: memcached
        {{- with .Values.memcached.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "scheduler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.memcached.podSecurityContext | default dict | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-memcached
          securityContext:
            {{- toYaml .Values.memcached.securityContext | default dict | nindent 12 }}
          image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
          ports:
            - name: memcached
              containerPort: 11211
              protocol: TCP
          {{- with .Values.memcached.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.memcached.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.memcached.resources | nindent 12 }}
      {{- with .Values.memcached.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.memcached.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.memcached.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler.fullname" . }}-memcached
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  type: {{ .Values.memcached.service.type }}
  ports:
    - port: {{ .Values.memcached.service.port }}
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    {{- include "scheduler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
