{{- if not .Values.scheduler.watttime.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scheduler.fullname" . }}-watttime
type: Opaque
stringData:
  WATTTIME_USERNAME: {{ .Values.scheduler.watttime.credentials.username }}
  WATTTIME_PASSWORD: {{ .Values.scheduler.watttime.credentials.password }}
{{- end }}