{{- if .Values.scheduler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler.fullname" . }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
    - port: {{ .Values.scheduler.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scheduler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
{{- end }}
