name: Package and release Helm chart

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  package:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: |
          helm lint helm/scheduler
          helm package helm/scheduler --destination dist

      - name: Upload .tgz to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger index update in carbon-aware/charts
        run: |
          curl -X POST https://api.github.com/repos/carbon-aware/charts/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.CARBON_AWARE_CHARTS_PAT }}" \
            -d '{"event_type":"chart-released"}'
